sudo: required
language: node_js
node_js: stable

# S: Build Lifecycle
cache:
  directories:
    - node_modules

install:
  - npm install
  - npm uninstall hexo-generator-index --save
  - npm install hexo-generator-index-pin-top --save
  # - npm install hexo-generator-search --save


#before_script:
 # - npm install -g gulp

script:
  - chmod 777 ./node_modules/.bin/hexo
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "DcmTruman"
  - git config user.email "695897983@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git pull --rebase origin master
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${myblog}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog_source
env:
 global:
   - GH_REF: github.com/DcmTruman/DcmTruman.github.io.git
